---
# Install Nginx

- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present
  become: yes

- name: Start and enable Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: Open firewall port 80
  ansible.posix.firewalld:
    port: "{{ nginx_listen_port }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  become: yes
  ignore_errors: yes
